import { readdirSync } from "node:fs";
import path from "node:path";
import {
  buildScrubbedEnv,
  type ExecutionContext,
  type Executor,
  type ExecutorEvent,
  evaluateToolCall,
  type StepExecutionRequest,
} from "@agrippa/executor-core";
import { type Options, type SDKMessage, query as sdkQuery } from "@anthropic-ai/claude-agent-sdk";

type QueryFn = (params: { prompt: string; options?: Options }) => AsyncIterable<SDKMessage>;

const ARTIFACT_DIR = ".agrippa/artifacts";

/** Prompt preamble telling the agent where declared artifacts must land. */
function artifactInstructions(expected: StepExecutionRequest["expectedArtifacts"]): string {
  // patch artifacts are generated by the engine from the git diff — the agent
  // must not hand-write them, or the engine skips its own diff (it sees the key
  // already produced) and stores the model's file instead of the real patch
  const authored = expected.filter((a) => a.kind !== "patch");
  if (authored.length === 0) return "";
  const list = authored
    .map(
      (a) =>
        `- ${ARTIFACT_DIR}/${a.key}${a.kind === "json" ? ".json" : a.kind === "markdown" ? ".md" : ""}`,
    )
    .join("\n");
  return [
    "",
    "---",
    "This step must produce the following artifact files (relative to the workspace root).",
    "Create each file with the final content before you finish:",
    list,
  ].join("\n");
}

function priorContextBlock(req: StepExecutionRequest): string {
  if (req.priorContext.length === 0) return "";
  const sections = req.priorContext
    .map((p) => `### Step ${p.stepId}\n${p.output.slice(0, 4000)}`)
    .join("\n\n");
  return `## Results from earlier steps\n\n${sections}\n\n---\n\n`;
}

/** Maps a StepExecutionRequest onto Claude Agent SDK query() options (docs/design/03). */
export function buildQueryArgs(
  req: StepExecutionRequest,
  _ctx: ExecutionContext,
  abortController: AbortController,
): { prompt: string; options: Options } {
  const agents: NonNullable<Options["agents"]> = {};
  for (const subagent of req.subagents) {
    agents[subagent.id] = {
      description: subagent.description,
      prompt: subagent.prompt,
      tools: subagent.tools.length > 0 ? subagent.tools : undefined,
      model: subagent.model.providerModelId as never,
    };
  }

  const mcpServers: NonNullable<Options["mcpServers"]> = {};
  for (const server of req.mcpServers) {
    if (server.transport === "stdio") {
      mcpServers[server.slug] = {
        type: "stdio",
        command: server.command,
        args: server.args,
        env: server.env,
      };
    } else {
      mcpServers[server.slug] = {
        type: server.transport,
        url: server.url,
        headers: server.headers,
      };
    }
  }

  // Only the skills we materialized are enabled — never whatever the checked-out
  // repo happens to ship under .claude/skills (docs/design/03 §Sandboxing).
  const skillNames = req.skills.map((s) => s.slug.split("/").pop() as string);
  const options: Options = {
    cwd: req.workspaceDir,
    model: req.model.providerModelId,
    systemPrompt: { type: "preset", preset: "claude_code", append: req.systemPrompt },
    agents: Object.keys(agents).length > 0 ? agents : undefined,
    mcpServers: Object.keys(mcpServers).length > 0 ? mcpServers : undefined,
    // skills load from <workspace>/.claude/skills; 'project' also pulls CLAUDE.md.
    // The worker strips repo-supplied .claude settings/hooks before this runs, so
    // 'project' cannot load attacker-controlled hooks or permission overrides.
    settingSources: ["project"],
    skills: skillNames.length > 0 ? skillNames : undefined,
    // ignore any .mcp.json in the checked-out repo — only our resolved servers
    strictMcpConfig: true,
    // OS-level command isolation when the host supports it (bubblewrap); degrade
    // gracefully elsewhere (e.g. macOS dev) rather than refusing to run
    sandbox: { enabled: true, failIfUnavailable: false },
    // secrets (master key, datastore URLs) must not reach the agent subprocess
    env: buildScrubbedEnv(),
    maxTurns: req.limits.maxTurns,
    includePartialMessages: true,
    resume: req.resumeSessionId,
    allowedTools: req.toolPolicy.allowedTools,
    disallowedTools: req.toolPolicy.disallowedTools,
    abortController,
    permissionMode: "acceptEdits",
    canUseTool: async (toolName, input) => {
      const decision = evaluateToolCall(
        req.toolPolicy,
        req.workspaceDir,
        toolName,
        input as Record<string, unknown>,
      );
      if (decision.behavior === "deny") return decision;
      return { behavior: "allow", updatedInput: input };
    },
  };

  const prompt = [
    priorContextBlock(req),
    req.instructions,
    artifactInstructions(req.expectedArtifacts),
  ].join("");

  return { prompt, options };
}

function textOf(content: Array<{ type: string; text?: string }>): string {
  return content
    .filter((block) => block.type === "text")
    .map((block) => block.text ?? "")
    .join("");
}

/**
 * Scans the artifact convention directory and emits one event per file that the
 * step actually contracted to produce. Scoping to `expected` (a) validates the
 * key/kind against the contract, (b) uses the declared kind rather than guessing
 * from the extension, (c) skips patch artifacts (the engine generates those),
 * and (d) ignores files left by earlier steps so a rescan can't re-emit them.
 */
function* collectArtifacts(
  workspaceDir: string,
  expected: StepExecutionRequest["expectedArtifacts"],
): Generator<ExecutorEvent> {
  const kindByKey = new Map(expected.map((a) => [a.key, a.kind] as const));
  const dir = path.join(workspaceDir, ARTIFACT_DIR);
  let entries: string[] = [];
  try {
    entries = readdirSync(dir);
  } catch {
    return;
  }
  const emitted = new Set<string>();
  for (const entry of entries) {
    const ext = path.extname(entry);
    const key = ext ? entry.slice(0, -ext.length) : entry;
    const kind = kindByKey.get(key);
    if (kind === undefined || kind === "patch" || emitted.has(key)) continue;
    emitted.add(key);
    yield { type: "artifact", key, kind, path: path.join(ARTIFACT_DIR, entry) };
  }
}

export function createClaudeExecutor(queryFn: QueryFn = sdkQuery as QueryFn): Executor {
  return {
    id: "claude-agent-sdk",
    capabilities: { subagents: true, mcp: true, skills: true, resume: true, streaming: true },

    async *executeStep(
      req: StepExecutionRequest,
      ctx: ExecutionContext,
    ): AsyncIterable<ExecutorEvent> {
      const abortController = new AbortController();
      const onAbort = () => abortController.abort();
      if (ctx.signal.aborted) onAbort();
      ctx.signal.addEventListener("abort", onAbort, { once: true });

      const { prompt, options } = buildQueryArgs(req, ctx, abortController);
      let started = false;
      let terminal: ExecutorEvent | null = null;

      try {
        for await (const message of queryFn({ prompt, options })) {
          switch (message.type) {
            case "system": {
              if ("subtype" in message && message.subtype === "init" && !started) {
                started = true;
                yield { type: "step.started", sessionId: message.session_id };
              }
              break;
            }
            case "stream_event": {
              const event = message.event as {
                type: string;
                delta?: { type?: string; text?: string };
              };
              if (
                event.type === "content_block_delta" &&
                event.delta?.type === "text_delta" &&
                event.delta.text
              ) {
                yield { type: "message.delta", text: event.delta.text };
              }
              break;
            }
            case "assistant": {
              const content = message.message.content as Array<{
                type: string;
                text?: string;
                id?: string;
                name?: string;
                input?: unknown;
              }>;
              const text = textOf(content);
              if (text) yield { type: "message.completed", role: "assistant", text };
              for (const block of content) {
                if (block.type === "tool_use") {
                  yield {
                    type: "tool.started",
                    toolName: block.name ?? "unknown",
                    input: block.input,
                    toolUseId: block.id ?? "",
                  };
                }
              }
              const usage = message.message.usage;
              if (usage) {
                yield {
                  type: "usage",
                  model: message.message.model ?? req.model.providerModelId,
                  inputTokens: usage.input_tokens ?? 0,
                  outputTokens: usage.output_tokens ?? 0,
                  cacheReadTokens: usage.cache_read_input_tokens ?? 0,
                  cacheWriteTokens: usage.cache_creation_input_tokens ?? 0,
                };
              }
              break;
            }
            case "user": {
              const content = (
                message as unknown as {
                  message: { content: unknown };
                }
              ).message.content;
              if (Array.isArray(content)) {
                for (const block of content as Array<{
                  type: string;
                  tool_use_id?: string;
                  content?: unknown;
                  is_error?: boolean;
                }>) {
                  if (block.type === "tool_result") {
                    yield {
                      type: "tool.completed",
                      toolUseId: block.tool_use_id ?? "",
                      output: block.content,
                      isError: block.is_error ?? false,
                    };
                  }
                }
              }
              break;
            }
            case "result": {
              if (message.subtype === "success") {
                terminal = { type: "step.completed", output: message.result };
              } else {
                terminal = {
                  type: "step.failed",
                  error: {
                    code: message.subtype === "error_max_turns" ? "model_error" : "internal",
                    message:
                      "errors" in message && message.errors.length > 0
                        ? message.errors.join("; ")
                        : message.subtype,
                  },
                };
              }
              break;
            }
            default:
              break;
          }
        }

        if (ctx.signal.aborted) {
          yield { type: "step.failed", error: { code: "aborted", message: "aborted" } };
          return;
        }
        if (terminal?.type === "step.completed") {
          yield* collectArtifacts(req.workspaceDir, req.expectedArtifacts);
        }
        yield terminal ?? {
          type: "step.failed",
          error: { code: "internal", message: "SDK stream ended without a result message" },
        };
      } catch (err) {
        if (ctx.signal.aborted) {
          yield { type: "step.failed", error: { code: "aborted", message: "aborted" } };
        } else {
          yield {
            type: "step.failed",
            error: { code: "model_error", message: String(err).slice(0, 2000) },
          };
        }
      } finally {
        ctx.signal.removeEventListener("abort", onAbort);
      }
    },
  };
}
