import { existsSync, realpathSync, rmSync } from "node:fs";
import path from "node:path";
import { isWithin } from "./isolation";
import type { ExecutorEvent, StepExecutionRequest } from "./types";

/**
 * The file-based artifact convention shared by workspace-writing executors:
 * a step's declared artifacts land in `.agrippa/artifacts/<key><ext>` and are
 * collected after success — contracted keys only, exact filenames only.
 */

export const ARTIFACT_DIR = ".agrippa/artifacts";

export type ExpectedArtifact = StepExecutionRequest["expectedArtifacts"][number];

/** The exact filename a declared artifact must be written to (key + kind's extension). */
export function expectedFilename(a: ExpectedArtifact): string {
  const ext = a.kind === "json" ? ".json" : a.kind === "markdown" ? ".md" : "";
  return `${a.key}${ext}`;
}

/** Prompt preamble telling the agent where declared artifacts must land. */
export function artifactInstructions(expected: StepExecutionRequest["expectedArtifacts"]): string {
  // patch artifacts are generated by the engine from the git diff — the agent
  // must not hand-write them, or the engine skips its own diff (it sees the key
  // already produced) and stores the model's file instead of the real patch
  const authored = expected.filter((a) => a.kind !== "patch");
  if (authored.length === 0) return "";
  const list = authored.map((a) => `- ${ARTIFACT_DIR}/${expectedFilename(a)}`).join("\n");
  return [
    "",
    "---",
    "This step must produce the following artifact files (relative to the workspace root).",
    "Create each file with the final content before you finish:",
    list,
  ].join("\n");
}

/** Prior-step outputs as a prompt preamble (cross-step state per ADR-0005). */
export function priorContextBlock(req: StepExecutionRequest): string {
  if (req.priorContext.length === 0) return "";
  const sections = req.priorContext
    .map((p) => `### Step ${p.stepId}\n${p.output.slice(0, 4000)}`)
    .join("\n\n");
  return `## Results from earlier steps\n\n${sections}\n\n---\n\n`;
}

/**
 * Emits one event per declared artifact whose **exact** contracted file exists.
 * Iterating the contract (not the directory) means a `json` artifact `report`
 * is matched only by `report.json`, never `report.md`; patch artifacts are
 * skipped (the engine generates those from the git diff); and files left by
 * earlier steps or written under other names are ignored.
 */
export function* collectArtifacts(
  workspaceDir: string,
  expected: StepExecutionRequest["expectedArtifacts"],
): Generator<ExecutorEvent> {
  const dir = path.join(workspaceDir, ARTIFACT_DIR);
  for (const a of expected) {
    if (a.kind === "patch") continue;
    const filename = expectedFilename(a);
    if (!existsSync(path.join(dir, filename))) continue;
    yield {
      type: "artifact",
      key: a.key,
      kind: a.kind,
      path: path.join(ARTIFACT_DIR, filename),
    };
  }
}

/** Delete this step's expected artifact files (patch excluded) before an attempt. */
export function clearExpectedArtifacts(
  workspaceDir: string,
  expected: StepExecutionRequest["expectedArtifacts"],
): void {
  const dir = path.join(workspaceDir, ARTIFACT_DIR);
  // refuse to touch the dir if it resolves (via a symlink an agent may have
  // created, e.g. `.agrippa -> /work`) outside the workspace — otherwise these
  // unlinks would reach the shared artifact store
  let realDir: string;
  try {
    realDir = realpathSync(dir);
  } catch {
    return; // missing dir → nothing to clear
  }
  if (!isWithin(realpathSync(workspaceDir), realDir)) return;
  for (const a of expected) {
    if (a.kind === "patch") continue;
    rmSync(path.join(dir, expectedFilename(a)), { force: true });
  }
}
